from src.sidebar_navigation import get_page_labels


DECISION_PAGE_OPTIONS = get_page_labels("决策")
ETF_PAGE_OPTIONS = get_page_labels("基金")
STOCK_PAGE_OPTIONS = get_page_labels("个股")
MONEY_PAGE_OPTIONS = get_page_labels("资金")
MACRO_PAGE_OPTIONS = get_page_labels("宏观")

DECISION_TODAY_PAGE_LABEL = "💼 今日机会清单"
DECISION_DAILY_RECO_PAGE_LABEL = "⭐ 每日趋势推荐"
DECISION_RECO_EVAL_PAGE_LABEL = "🧪 推荐评估"
DECISION_ML_PAGE_LABEL = "🧠 ML预测升级"

ETF_MAIN_PAGE_LABEL = "📈 主要宽基ETF份额"
ETF_RATIO_PAGE_LABEL = "🥧 ETF分类占比"
ETF_TREND_PAGE_LABEL = "📈 ETF分类趋势"
ETF_WIDE_INDEX_PAGE_LABEL = "📊 宽基指数ETF"
ETF_FUND_MONITOR_PAGE_LABEL = "📈 基金监测"

STOCK_SECURITY_SEARCH_LABEL = "🔎 个股/指数查询"
STOCK_COMPANY_SCREENER_LABEL = "🏢 公司筛选"
STOCK_TECH_PICKER_LABEL = "🎯 技术选股"

MONEY_FLOW_PAGE_LABEL = "💹 资金流向"
MONEY_VOLUME_PAGE_LABEL = "📊 每日成交量"
MONEY_FUND_HOT_PAGE_LABEL = "🏦 公募持仓热股"
MONEY_LIMITUP_PAGE_LABEL = "🔥 打板情绪"
MONEY_HOTMONEY_PAGE_LABEL = "🧾 游资名录"

MACRO_MAIN_PAGE_LABEL = "🌏 宏观经济"
MACRO_DEPOSIT_PAGE_LABEL = "🏦 本外币存款"
MACRO_INDEX_MONITOR_PAGE_LABEL = "📊 指数监测"
