[theme]
primaryColor = "#533AFD"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F6F9FC"
textColor = "#0D253D"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
